"""initial baseline

Revision ID: db7ffc2db40e
Revises: 
Create Date: 2026-03-10 18:05:34.638715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7ffc2db40e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check busy_slots
    busy_slots_columns = [c['name'] for c in inspector.get_columns('busy_slots')]
    if 'connection_id' not in busy_slots_columns:
        op.add_column('busy_slots', sa.Column('connection_id', sa.Integer(), nullable=True))
        op.create_foreign_key('fk_busy_slots_connection', 'busy_slots', 'calendar_connections', ['connection_id'], ['id'])
    
    # Check users
    users_columns = [c['name'] for c in inspector.get_columns('users')]
    if 'email' not in users_columns:
        op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    
    # Drop columns if they exist
    if 'google_refresh_token' in users_columns:
        op.drop_column('users', 'google_refresh_token')
    if 'apple_auth_data' in users_columns:
        op.drop_column('users', 'apple_auth_data')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('apple_auth_data', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('google_refresh_token', sa.TEXT(), nullable=True))
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'busy_slots', type_='foreignkey')
    op.drop_column('busy_slots', 'connection_id')
    # ### end Alembic commands ###
